apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid-prometheus-exporter.fullname" . }}
  labels:
    {{- include "druid-prometheus-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/port: "7000"    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "druid-prometheus-exporter.selectorLabels" . | nindent 4 }}
